config/routes.rb
Rails.application.routes.draw do
  resources :labels
  get 'sessions/new'
  resources :tasks
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'tasks#index'
  namespace :admin do
    resources :users, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  end
  resources :products, only: :show do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
  belongs_to :user
  validates :name, presence: true
  validates :details, presence: true
  enum task_stutas:{未着手:1, 着手中:2, 完了:3}
  enum priority:{高:1, 中:2, 低:3}
  scope :search_name, -> (name){ where("name LIKE?","%#{name}%") }
  scope :search_stutas, -> (stutas){ where(stutas: stutas) }
  scope :search_priority, -> (priority){ where(priority: priority) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tasks
  validates :email, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 },on: :create
  before_destroy :admin_check

  def admin_check
    @user = User.all
    throw(:abort) if @user.count('true') <= 1
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :show]

  def index
    if current_user.admin?
      @users = User.all.includes(:tasks)
    else
      redirect_to tasks_path, notice: '管理者のみ閲覧できるページです。'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザーを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザーを削除しました。"
    else
      redirect_to admin_users_path, notice: "管理者がいなくなるのでユーザーを削除できません。"
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[ show edit update destroy ]

  # GET /labels or /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1 or /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: "Label was successfully created." }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: "Label was successfully updated." }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: "Label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  PER = 8
  def index
    if params[:sort_expired]
      @tasks = Task.order(limit: :asc).page(params[:page]).per(PER)
    elsif params[:sort_priority]
      @tasks = Task.order(priority: :asc).page(params[:page]).per(PER)
    elsif params[:name].present? && params[:stutas].present?
      @tasks = Task.where(name: params[:name]).page(params[:page]).per(PER)
      @tasks = @tasks.where(stutas: params[:stutas]).page(params[:page]).per(PER)
    elsif params[:name].present?
      @tasks = Task.where(name: params[:name]).page(params[:page]).per(PER)
    elsif params[:stutas].present?
      @tasks = Task.where(stutas: params[:stutas]).page(params[:page]).per(PER)
    elsif params[:priority].present?
      @tasks = Task.where(priority: params[:priority]).page(params[:page]).per(PER)
    else
      @tasks = Task.all.page(params[:page]).per(PER)
      @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    #省略
    if @task.save
    # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to tasks_path, notice: "タスクを作成しました！"
    else
    # 入力フォームを再描画します。
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました！"
  end

private
  def task_params
    params.require(:task).permit(:name, :details, :id, :limit, :stutas, :priority, :sort_expired, :user_id, :title, { label_ids: [] })
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @tasks = Task.all
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to tasks_path
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<%= form_with(model: [:admin,@user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  アカウント権限：<%= f.select :admin, { 一般: false, 管理者: true } %>
  <%= f.submit "Edit user account" %>
<% end %>

app/views/admin/users/index.html.erb
<h1>管理画面</h1>
<td><%= link_to "ラベル管理", labels_path, class: 'btn btn-primary' %></td>
<table>
<% @users.each do |user| %>
<tr>
  <th>ID</th>
  <td><%= user.id %></td>
</tr
<tr>
  <th>名前</th>
  <td><%= user.name %></td>
</tr>
<tr>
  <th>アドレス</th>
  <td><%= user.email %></td>
</tr>
<tr>
  <th>権限</th>
  <td><% if user.admin? %>管理者<% else %>一般ユーザー<% end %></td>
</tr>
<tr>
  <th>タスク数</th>
  <td><%= user.tasks.count %></td>
  <td><%= link_to "詳細", admin_user_path(user), class: 'btn btn-primary' %></td>
  <td><%= link_to "編集", edit_admin_user_path(user), class: 'btn btn-success' %></td>
  <td><%= link_to '削除', admin_user_path(user), method: :delete, class: 'btn btn-danger' %></td>
</tr>

<% end %>
</table>

<%= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<%= form_with(model: [:admin,@user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  アカウント権限：<%= f.select :admin, { 一般: false, 管理者: true } %>
  <%= f.submit "Edit my account" %>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<table class="table table-striped">
  <tr>
    <th>名前</th>
    <th>詳細</th>
    <th>終了期限</th>
    <th>ステータス</th>
    <th>優先順位</th>
  </tr>
  <%= link_to "編集", edit_admin_user_path(@user), class: 'btn btn-success' %>
  <%= link_to '削除', admin_user_path(@user), method: :delete, class: 'btn btn-danger' %>

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Labels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path %>
<%= link_to '管理者画面に戻る', admin_users_path %>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manyo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class="header">
    <nav>
      <ul class="top_menu clearfix">
        <li><%= link_to 'ホーム', tasks_path %></li>
        <li><%= link_to 'タスク登録', new_task_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Profile", user_path(current_user.id), id: 'Profile' %></li>
          <li><%= link_to "Logout", session_path(current_user.id), id: 'Logout', method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "Login", new_session_path %></li>
        <% end %>
          <li><%= link_to '管理者画面', admin_users_path, id: 'kanri' %></li>
      </ul>
    </nav>
  </header>
  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="task_name">
    <%= form.label :タイトル %>
    <%= form.text_field :name %>
  </div>
  <div class="task_details">
    <%= form.label :詳細 %>
    <%= form.text_field :details %>
  </div>
  <div class="row">
  <div class="col-xs-1">
    <label class="control-label" for="">終了期限</label>
    <%= form.date_select :limit, {}, class: 'form-control' %>
    </div>
  </div>
  <div class="task_stutas">
    <%= form.label :ステータス %>
    <%= form.select :stutas, [["未着手", "未着手"], ["着手中", "着手中"], ["完了", "完了"]], include_blank: "選択して下さい" %>
  </div>
  <div class="task_priority>
    <%= form.label :優先順位 %>
    <%= form.select :priority, [["高", "高"], ["中", "中"], ["低", "低"]], include_blank: "選択して下さい" %>
  </div>
  <%= form.label :ラベル %>
  <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  <%= form.submit "作成する" %>
<% end %>
<%= link_to '一覧へ戻る', tasks_path %>

app/views/tasks/edit.html.erb
<h2>タスクを編集する</h2>
  <%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<div class="search-form">
  <%= form_with(model: @task, url: tasks_path, method: :get, local: true) do |f| %>
    <div class="field">
      <%= f.label :name, "タスク名" %>
      <%= f.text_field :name, id:"search_text" %>
      <%= f.label :stutas, 'ステータス' %>
      <%= f.select :stutas, Task.task_stutas.keys, include_blank:"-" %>
      <%= f.label :priority, '優先順位' %>
      <%= f.select :priority, Task.priorities.keys, include_blank:"-" %>
      <%= f.label :label, 'ラベル' %>
      <%= f.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
      <button type="submit" id="search_btn" class="btn btn-primary btn-s">検索</button>
    </div>
  <% end %>
<table class="table table-striped">
  <tr>
    <th>名前</th>
    <th>詳細</th>
    <th><%= link_to "終了期限 ▼", tasks_path(sort_expired: "true"), class:"sort_limit" %></th>
    <th>ステータス</th>
    <th><%= link_to "優先順位 ▼", tasks_path(sort_priority: "true") %></th>
    <th>ラベル</th>
  </tr>
<% @tasks.each do |task| %>
<% if task.user == current_user %>
  <tr>
    <td class="task_list"><%= task.name %></td>
    <td><%= task.details %></td>
    <td><%= task.limit %></td>
    <td><%= task.stutas %></td>
    <td><%= task.priority %></td>
    <td>
      <% task.labels.each do |label| %>
      <%= label.name %>
      <% end %>
    </td>
    <td><%= link_to '詳細', task_path(task.id), class: 'btn btn-primary' %></td>
    <td><%= link_to "編集", edit_task_path(task.id), class: 'btn btn-success' %></td>
    <td><%= link_to '削除', task_path(task.id), method: :delete, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
<% end %>
<%= paginate @tasks %>
</table>

app/views/tasks/new.html.erb
<h2>タスクを作成する</h2>
  <%= render 'form' %>

app/views/tasks/show.html.erb
<h1>タスク詳細画面</h1>
<p>名前: <%= @task.name %></p>
<p>詳細: <%= @task.details %></p>
<p>終了期限: <%= @task.limit %></p>
<p>ステータス: <%= @task.stutas %></p>
<p>優先順位: <%= @task.priority %></p>
<p>登録ラベル:</p>
<% @task.labels.each do |label| %>
<%= label.name %>
<% end %>
<br>
<br>
<%= link_to '一覧へ戻る', tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<table class="table table-striped">
  <tr>
    <th>名前</th>
    <th>詳細</th>
    <th>終了期限</th>
    <th>ステータス</th>
    <th>優先順位</th>
  </tr>
<% @tasks.each do |task| %>
<% if task.user == current_user %>
  <tr class="task_list">
    <td><%= task.name %></td>
    <td><%= task.details %></td>
    <td><%= task.limit %></td>
    <td><%= task.stutas %></td>
    <td><%= task.priority %></td>
    <td><%= link_to '詳細', task_path(task.id), class: 'btn btn-primary' %></td>
    <td><%= link_to "編集", edit_task_path(task.id), class: 'btn btn-success' %></td>
    <td><%= link_to '削除', task_path(task.id), method: :delete, class: 'btn btn-danger' %></td>
  </tr>
<% end %>
<% end %>